// packages/app/src/modules/ProfileStack/EditProfile.tsx
import format from "date-fns/format";
import { Formik } from "formik";
import React, { useRef } from "react";
import { Platform, ScrollView, View } from "react-native";
import { useMutation, useQuery, useQueryCache } from "react-query";
const yup = require("yup");
import { initialProfileData } from "../../constants";
import { DatePickerField } from "../../form-fields/DatePickerField";
import { FlairSelectField } from "../../form-fields/FlairSelectField";
import { RadioGroupField } from "../../form-fields/RadioGroupField";
import { TextField } from "../../form-fields/TextField";
import { defaultMutationFn } from "../../Providers";
import { registerForPushNotifications } from "../../registerForPushNotifications";
import { MeResponse } from "../../types";
import { CheckboxWithLabel } from "../../ui/CheckboxWithLabel";
import { ErrorText } from "../../ui/ErrorText";
import { Flair } from "../../ui/Flair";
import { FormSpacer } from "../../ui/FormSpacer";
import { FullscreenLoading } from "../../ui/FullscreenLoading";
import { KeyboardAwareScrollView } from "../../ui/KeyboardAwareScrollView";
import { Label } from "../../ui/Label";
import { LoadingButton } from "../../ui/LoadingButton";
import { LocationAutocomplete } from "../../ui/LocationAutocomplete";
import { MyTextInput } from "../../ui/MyTextInput";
import { ScreenWrapper } from "../../ui/ScreenWrapper";
import { getAge, userToInitialFormData } from "../../utils";
import { ProfileStackNav } from "./ProfileNav";

const schema = yup.object().shape({
  displayName: yup.string().required().max(50),
  bio: yup.string().required().max(150),
  ageRangeMax: yup.number().required().min(18).max(150),
  ageRangeMin: yup.number().required().min(18).max(150),
});

export const EditProfile: React.FC<ProfileStackNav<"editProfile">> = ({
  navigation,
}) => {
  const scrollView = useRef<ScrollView>(null);
  const { data, isLoading } = useQuery<MeResponse>("/me");
  const cache = useQueryCache();
  const [mutate, { isLoading: mutIsLoading }] = useMutation(defaultMutationFn);

  if (isLoading) {
    return <FullscreenLoading />;
  }

  return (
    <ScreenWrapper>
      <Formik
        initialValues={
          data?.user ? userToInitialFormData(data.user) : initialProfileData
        }
        validateOnChange={false}
        validateOnBlur={false}
        validationSchema={schema}
        onSubmit={async ({ sendNotifs, ...values }) => {
          const d: any = {
            ...values,
            ageRangeMax: parseInt(values.ageRangeMax),
            ageRangeMin: parseInt(values.ageRangeMin),
            birthday: format(values.birthday, "yyyy-MM-dd"),
          };

          if (data!.user!.hasPushToken !== sendNotifs) {
            if (sendNotifs) {
              const t = await registerForPushNotifications();
              if (t) {
                d.pushToken = t;
              }
            } else {
              d.pushToken = null;
            }
          }
          try {
            const { user } = await mutate(["/user", d, "PUT"]);
            cache.setQueryData("/me", { user });
            cache.invalidateQueries("/feed");
            if (data!.user!.codeImgIds.length) {
              navigation.goBack();
            } else {
              navigation.navigate(`codeSnippeter`, { replace: true });
            }
          } catch {}
        }}
      >
        {({ values, setFieldValue, handleSubmit, errors }) => {
          const age = getAge(values.birthday);
          const tooYoung = age < 18 && Platform.OS === "ios";
          return (
            <KeyboardAwareScrollView
              ref={scrollView}
              showsVerticalScrollIndicator={false}
              keyboardShouldPersistTaps="handled"
            >
              <FormSpacer>
                <TextField name="displayName" label="Name" />
              </FormSpacer>
              <FormSpacer>
                <TextField name="bio" label="Bio" multiline />
              </FormSpacer>
              <FormSpacer>
                <FlairSelectField
                  name="flair"
                  label={
                    values.flair ? (
                      <Flair name={values.flair as any} />
                    ) : (
                      "Flair"
                    )
                  }
                />
              </FormSpacer>
              <FormSpacer>
                <DatePickerField
                  name="birthday"
                  label={`Birthday (used to compute age: ${age})`}
                />
                {tooYoung ? (
                  <ErrorText>
                    You need to be 18 or older to use the app.
                  </ErrorText>
                ) : null}
              </FormSpacer>
              <FormSpacer>
                <RadioGroupField
                  name="goal"
                  label="I'm looking for:"
                  onValue={(v) => {
                    if (v === "friendship") {
                      values.ageRangeMin = initialProfileData.ageRangeMin;
                      values.ageRangeMax = initialProfileData.ageRangeMax;
                    }
                  }}
                  options={[
                    ...(age >= 18
                      ? [
                          {
                            label: "love",
                            value: "love",
                          },
                        ]
                      : []),
                    { label: "friendship", value: "friendship" },
                  ]}
                />
              </FormSpacer>
              {values.goal === "love" ? (
                <>
                  <FormSpacer>
                    <RadioGroupField
                      name="gender"
                      label="Gender:"
                      options={[
                        { label: "male", value: "male" },
                        { label: "female", value: "female" },
                        { label: "non-binary", value: "non-binary" }
                      ]}
                    />
                  </FormSpacer>
                  <FormSpacer>
                    <RadioGroupField
                      name="genderToShow"
                      label="Show me code from:"
                      options={[
                        { label: "males", value: "male" },
                        { label: "females", value: "female" },
                        { label: "everyone", value: "everyone" },
                      ]}
                    />
                  </FormSpacer>
                  <FormSpacer>
                    <View style={{ marginBottom: 8 }}>
                      <Label>Age Range: </Label>
                    </View>
                    <View style={{ flexDirection: "row" }}>
                      <MyTextInput
                        keyboardType="numeric"
                        value={values.ageRangeMin}
                        onChangeText={(x) => setFieldValue("ageRangeMin", x)}
                      />
                      <MyTextInput
                        style={{ marginLeft: 16 }}
                        keyboardType="numeric"
                        value={"" + values.ageRangeMax}
                        onChangeText={(x) => setFieldValue("ageRangeMax", x)}
                      />
                    </View>
                    {errors.ageRangeMax ? (
                      <ErrorText style={{ marginTop: 8 }}>
                        {errors.ageRangeMax}
                      </ErrorText>
                    ) : null}
                    {errors.ageRangeMin ? (
                      <ErrorText style={{ marginTop: 4 }}>
                        {errors.ageRangeMin}
                      </ErrorText>
                    ) : null}
                  </FormSpacer>
                  <FormSpacer>
                    <View style={{ marginBottom: 4 }}>
                      <Label>City: </Label>
                    </View>
                    <LocationAutocomplete
                      defaultValue={values.location}
                      onFocus={() => {
                        scrollView.current?.scrollToEnd();
                      }}
                      onLocation={(x) => {
                        setFieldValue("location", x);
                      }}
                    />
                    <View style={{ marginTop: 6 }}>
                      <CheckboxWithLabel
                        checked={values.global}
                        onPress={() => setFieldValue("global", !values.global)}
                        label="see people from around the world after you've run out of profiles nearby"
                      />
                    </View>
                  </FormSpacer>
                </>
              ) : null}
              <FormSpacer>
                <View style={{ marginBottom: 4 }}>
                  <Label>Notifications: </Label>
                </View>
                <CheckboxWithLabel
                  checked={values.sendNotifs}
                  onPress={() =>
                    setFieldValue("sendNotifs", !values.sendNotifs)
                  }
                  label="send me them on new matches/messages"
                />
              </FormSpacer>
              <View style={{ paddingTop: 10 }}>
                {tooYoung ? null : (
                  <LoadingButton
                    isLoading={mutIsLoading}
                    onPress={() => handleSubmit()}
                  >
                    {data!.user!.codeImgIds.length ? "save" : "next"}
                  </LoadingButton>
                )}
              </View>
              <View style={{ height: 30 }} />
            </KeyboardAwareScrollView>
          );
        }}
      </Formik>
    </ScreenWrapper>
  );
};

// svelte-stuff/screens/EditProfile.svelte
<script lang="ts">
  import { onMount } from "svelte";

  import { flairOptions } from "../shared/constants";

  import { mutation } from "../shared/mutation";
  import type { ProfileFormData, User } from "../shared/types";
  import { getAge } from "../shared/utils";
  import Flair from "../ui/Flair.svelte";
  import InputField from "../ui/InputField.svelte";
  import LoadingButton from "../ui/LoadingButton.svelte";
  import LocationAutocomplete from "../ui/LocationAutocomplete.svelte";
  import RadioGroup from "../ui/RadioGroup.svelte";
  import SelectField from "../ui/SelectField.svelte";

  export let onNext: (u: User) => void;
  export let data: ProfileFormData;
  export let buttonText: string;
  let form: HTMLFormElement;
  const currentYear = new Date().getFullYear();
  let disabled = false;

  $: age =
    data.year && data.month && data.day
      ? getAge(
          new Date(
            parseInt(data.year),
            parseInt(data.month),
            parseInt(data.day)
          )
        )
      : null;

  $: {
    if (data.year && data.month && data.day) {
      const age = getAge(
        new Date(parseInt(data.year), parseInt(data.month), parseInt(data.day))
      );
      if (age < 18 && data.goal !== "friendship") {
        data.goal = "friendship";
      }
    }
  }
</script>

<style>
  .label {
    margin-bottom: 4px;
    font-size: calc(var(--vscode-font-size) * 0.9);
  }
  form > div {
    margin-bottom: 30px;
  }
  .row {
    display: flex;
  }
  .row > div {
    min-width: 40px;
  }
  span {
    width: 10px;
  }
  [type="checkbox"] {
    vertical-align: middle;
  }
</style>

<form
  bind:this={form}
  disabled
  on:submit={() => false}
  style="margin-top: 20px;">
  <div>
    <InputField
      required
      name="displayName"
      label="Name"
      bind:value={data.displayName} />
  </div>
  <div>
    <InputField
      required
      textArea
      name="bio"
      label="Bio"
      bind:value={data.bio} />
  </div>
  <div>
    <SelectField
      bind:value={data.flair}
      name="flair"
      label="Flair:"
      options={flairOptions} />
    <Flair flair={data.flair} />
  </div>
  <div>
    <div class="label">
      Birthday (used to compute age:
      {getAge(new Date(parseInt(data.year), parseInt(data.month), parseInt(data.day)))})
    </div>
    <div class="row">
      <SelectField
        required
        bind:value={data.month}
        name="month"
        options={[{ value: '', label: 'Month' }, { value: '1', label: 'Jan' }, { value: '2', label: 'Feb' }, { value: '3', label: 'Mar' }, { value: '4', label: 'Apr' }, { value: '5', label: 'May' }, { value: '6', label: 'Jun' }, { value: '7', label: 'Jul' }, { value: '8', label: 'Aug' }, { value: '9', label: 'Sep' }, { value: '10', label: 'Oct' }, { value: '11', label: 'Nov' }, { value: '12', label: 'Dec' }]} />
      <span />
      <SelectField
        required
        bind:value={data.day}
        name="day"
        options={[{ value: '', label: 'Day' }, ...Array.from(
            Array(31),
            (_, i) => ({
              value: `${i + 1}`,
              label: `${i + 1}`,
            })
          )]} />
      <span />
      <SelectField
        required
        bind:value={data.year}
        name="year"
        options={[{ value: '', label: 'Year' }, ...Array.from(
            Array(120),
            (_, i) => ({
              label: `${currentYear - i}`,
              value: `${currentYear - i}`,
            })
          )]} />
    </div>
  </div>
  <div>
    <div class="label">I'm looking for:</div>
    <RadioGroup
      bind:value={data.goal}
      options={[{ label: age && age < 18 ? 'love 18+' : 'love', value: 'love' }, { label: 'friendship', value: 'friendship' }]} />
  </div>
  {#if data.goal === 'love'}
    <div>
      <div class="label">Gender:</div>
      <RadioGroup
        bind:value={data.gender}
        options={[{ label: 'male', value: 'male' }, { label: 'female', value: 'female' }, { label: 'non-binary', value: 'non-binary' }]} />
    </div>
    <div>
      <div class="label">Show me code from:</div>
      <RadioGroup
        bind:value={data.genderToShow}
        options={[{ label: 'males', value: 'male' }, { label: 'females', value: 'female' }, { label: 'everyone', value: 'everyone' }]} />
    </div>
    <div>
      <div class="label">Age Range:</div>
      <div class="row">
        <div class="row">
          <InputField
            required
            type="number"
            min={18}
            max={150}
            name="minAgeRange"
            placeholder="18"
            bind:value={data.ageRangeMin} />
        </div>
        <span />
        <div class="row">
          <InputField
            required
            placeholder="24"
            type="number"
            min={18}
            max={150}
            name="maxAgeRange"
            bind:value={data.ageRangeMax} />
        </div>
      </div>
    </div>
    <div>
      <LocationAutocomplete
        required
        name="location"
        label="City"
        bind:value={data.location} />
      <div style="margin-top: 6px;">
        <label for="global" style="word-wrap:break-word">
          <input id="global" type="checkbox" bind:checked={data.global} />see
          people from around the world after you've run out of profiles nearby
        </label>
      </div>
    </div>
  {/if}
  <div style="padding-top: 20px;">
    <LoadingButton
      on:click={async () => {
        if (!form.reportValidity()) {
          return;
        }
        disabled = true;
        try {
          const { year, month, day, ...values } = data;
          const { user } = await mutation('/user', { ...values, birthday: `${year}-${month.length === 1 ? '0' + month : month}-${day.length === 1 ? '0' + day : day}` }, { method: 'PUT' });
          onNext(user);
        } catch {}
        disabled = false;
      }}
      type="button"
      {disabled}>
      {#if disabled}loading{:else}{buttonText}{/if}
    </LoadingButton>
  </div>
</form>
